### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'main'

### ISSUE THREAD

**Issue by cuckoo-linux** [Tencent/HaboMalHunter#12]
habo@habo-VirtualBox:~/HaboMalHunter$ sudo python AnalyzeControl.py -v -l ./test/bin/read.64.elf
Traceback (most recent call last):
  File "AnalyzeControl.py", line 688, in <module>
    ret = main(len(sys.argv), sys.argv)
  File "AnalyzeControl.py", line 615, in main
    cfg = init_arguments(argv)
  File "AnalyzeControl.py", line 156, in init_arguments
    cfg = init_cfg(args.config_path,args)
  File "AnalyzeControl.py", line 96, in init_cfg
    for k,v in conf_parser.items(SECTION_DEF):
  File "/usr/lib/python2.7/ConfigParser.py", line 642, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'main'

**Comment by jingleyang** [comment]
hi,
The issue is related with config.ini. By default, the configuration file is config.ini in the first level of source code. Please try to use option `-e CONFIG_PATH` , to point config file path explicitly. And check whether a section named [main] exists in the config file.
Thanks

**Comment by Kai-King** [comment]
Excuse me, Can you solve it? this is my config.ini.
`root@host:~/HaboMalHunter# cat config.ini 
# Tencent is pleased to support the open source community by mak
# Copyright (C) 2017 THL A29 Limited, a Tencent company. All rig
# Licensed under the MIT License (the "License"); you may not us
# compliance with the License. You may obtain a copy of the Lice
# 
# http://opensource.org/licenses/MIT
# 
# Unless required by applicable law or agreed to in writing, sof
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# either express or implied. See the License for the specific la
# and limitations under the License.

[main]
# Version
version = 2.0.0.3
# log
log_dir = log
file_log = system.log
static_log = output.static
dynamic_log = output.dynamic

# home dir, discard, current is the parent dir of the target
exec_home = workspace

# time limitation (seconds)
time_limit_dynamic = 10
`
