### ISSUE TITLE
Errors on execution

### ISSUE THREAD

**Issue by Evan-Sa** [Tencent/HaboMalHunter#9]
Followed the instructions on Readme but receivedthe following error messages upon execution.  

~/HaboMalHunter$ sudo python AnalyzeControl.py -v -l ./test/bin/read.32.elf
Traceback (most recent call last):
  File "AnalyzeControl.py", line 688, in <module>
    ret = main(len(sys.argv), sys.argv)
  File "AnalyzeControl.py", line 615, in main
    cfg = init_arguments(argv)
  File "AnalyzeControl.py", line 156, in init_arguments
    cfg = init_cfg(args.config_path,args)
  File "AnalyzeControl.py", line 96, in init_cfg
    for k,v in conf_parser.items(SECTION_DEF):
  File "/usr/lib/python2.7/ConfigParser.py", line 642, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'main'

**Comment by 14m3** [comment]
I encounter the same problem, how to solve it?

**Comment by cuckoo-linux** [comment]
@Evan-Sa : has your problem solved??

**Comment by jingleyang** [comment]
Check https://github.com/Tencent/HaboMalHunter/issues/12
Thanks
